### ISSUE TITLE
pytest-splinter does not work with splinter>=0.18.0

### ISSUE THREAD

**Issue by enkidulan** [pytest-dev/pytest-splinter#169]
```

    def patch_webdriverelement():  # pragma: no cover
        """Patch the WebDriverElement to allow firefox to use mouse_over."""
    
        def mouse_over(self):
            """Perform a mouse over the element which works."""
            (
                ActionChains(self.parent.driver)
                .move_to_element_with_offset(self._element, 2, 2)
                .perform()
            )
    
        # Apply the monkey patch for Firefox WebDriverElement
>       firefox.WebDriverElement.mouse_over = mouse_over
E       AttributeError: module 'splinter.driver.webdriver.firefox' has no attribute 'WebDriverElement'

.venv/lib64/python3.10/site-packages/pytest_splinter/splinter_patches.py:21: AttributeError
```

**Comment by mpasternak** [comment]
Hmmm somehow I thought that I already patched it. 

Can you submit a pull request?

**Comment by jpic** [comment]
Should we really keep patch_webdriverelement?

After all, it's implementation, while still being different parameters than pytest-splinter, is expected to work?

Meanwhile, the workaround is to short circuit patch_webdriverelement ie.:

```python
  9 def patch_webdriverelement():  # pragma: no cover
 10     """Patch the WebDriverElement to allow firefox to use mouse_over."""
 11     return
```

Unfortunnately, I don't have anything with mouse_over to test my project without the monkey patch.

**Comment by jpic** [comment]
@mpasternak yes, you fixed it in 0f9cae60
But it's not in pypi

**Comment by mpasternak** [comment]
@jpic looks like it's time for a new release then.

**Comment by jpic** [comment]
Just confirmed this locally with dal
Thanks :pray: 
Keep up the gr8 work :tophat:

**Comment by mpasternak** [comment]
@jpic how do you feel about testing pytest-splinter 3.3.2

**Comment by jpic** [comment]
Working for me! Thanks! Gratz 4 teh release :guitar:

**Comment by mpasternak** [comment]
"No... you're breathtaking!" Thanks!
